# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

### Not for Grading

# Titanic Dataset Preprocessing Assignment

In this assignment, we will preprocess the Titanic dataset to practice data cleaning, encoding, scaling, binarization, polynomial features, discretization, power transformation, and feature selection. We will use Scikit-learn's preprocessing functions to make the data ready for machine learning.

### Objectives:
- Handle missing values
- Encode categorical variables
- Scale features
- Apply binarization and discretization
- Generate polynomial features
- Perform power transformation
- Select the top features

## Setup Steps

In [ ]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "aiml_pg_27" #@param {type:"string"}

In [ ]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "7896987896" #@param {type:"string"}

In [ ]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython

ipython = get_ipython()

notebook= "U1W2_03_Titanic_Preprocessing_sklearn" #name of the notebook
Answer = "Ungraded"
def setup():
#  ipython.magic("sx pip3 install torch")
    from IPython.display import HTML, display
    ipython.magic("sx wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/Purchase_Dataset.csv")
    display(HTML('<script src="https://dashboard.talentsprint.com/submissions/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():

    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword(), "batch" : "IIITH-PG-AIML-27"}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getComplexity() and getAdditional() and getConcepts() and getComments():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "id" : Id, "file_hash" : file_hash,
              "feedback_experiments_input" : Comments, "notebook" : notebook, "batch" : "IIITH-PG-AIML-27"}

      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://learn-iiith.talentsprint.com/notebook_submissions")
        # print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
      return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None
def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None

def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()

else:
  print ("Please complete Id and Password cells before running setup")

Please complete Id and Password cells before running setup

In [ ]:
# Loading the dataset
import pandas as pd
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
data = pd.read_csv(url)

PassengerId: A unique sequential identifier assigned to each passenger.

Survived: Indicates if the passenger survived ($1$) or died ($0$).

Pclass: The ticket class (1st, 2nd, or 3rd), serving as a proxy for socio-economic status.

Name: The full name of the passenger, including titles (e.g., Mr., Mrs., Miss.).

Sex: The biological sex of the passenger (male or female).

Age: The age of the passenger in years (fractional if under 1).

SibSp: The number of siblings and/or spouses the passenger had aboard.

Parch: The number of parents and/or children the passenger had aboard.

Ticket: The unique ticket number issued to the passenger.

Fare: The amount of money paid for the travel ticket.

Cabin: The cabin number where the passenger was stayed (contains many missing values).

Embarked: The port where the passenger boarded the Titanic (C = Cherbourg, Q = Queenstown, S = Southampton).

In [ ]:
print("First 5 rows of the dataset:\n")
data.head()

First 5 rows of the dataset:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
data[data['Age'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
data.shape

(891, 12)

In [ ]:
data.shape

(891, 12)

In [ ]:
891-714

177

In [ ]:
print("\nDataset information:")
data.info()

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
set(data['Embarked'])

{'C', 'Q', 'S', nan}

In [ ]:
data['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

## Step 2: Handling Missing Values

In [ ]:
from sklearn.impute import SimpleImputer
# Impute numerical columns
imputer_num = SimpleImputer(strategy="median")
data["Age"] = imputer_num.fit_transform(data[["Age"]])
# data["Fare"] = imputer_num.fit_transform(data[["Fare"]])
print("\nAfter imputing numerical columns:\n", data[["Age", "Fare"]].head())

After imputing numerical columns:
     Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [ ]:
# imputer_cat.fit_transform(data[["Embarked"]]) it will give 2d as string for numric 1d so we used ravel()

In [ ]:
# Impute categorical columns
imputer_cat = SimpleImputer(strategy="most_frequent")
data["Embarked"] = imputer_cat.fit_transform(data[["Embarked"]]).ravel()
print("\nAfter imputing categorical column 'Embarked':\n", )
data["Embarked"].head()

After imputing categorical column 'Embarked':

0    S
1    C
2    S
3    S
4    S
Name: Embarked, dtype: object

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## Step 3: Encoding Categorical Variables

In [ ]:
# pd.DataFrame([['A','B','C'],[]])

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Label Encoding for binary categorical column 'Sex'
le = LabelEncoder()
data["Sex"] = le.fit_transform(data["Sex"])
print("\nAfter label encoding 'Sex':\n", data["Sex"].head())

# One-hot encoding for multi-category columns
data = pd.get_dummies(data, columns=["Embarked", "Pclass"], drop_first=True)
print("\nAfter one-hot encoding 'Embarked' and 'Pclass':\n")
data.head()

After label encoding 'Sex':
 0    1
1    0
2    0
3    0
4    1
Name: Sex, dtype: int64

After one-hot encoding 'Embarked' and 'Pclass':

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_Q,Embarked_S,Pclass_2,Pclass_3
0,1,0,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,False,True,False,True
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,False,False,False,False
2,3,1,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,False,True,False,True
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,False,True,False,False
4,5,0,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,False,True,False,True

## Step 4: Feature Scaling

In [ ]:
data[['Fare']]

        Fare
0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
..       ...
886  13.0000
887  30.0000
888  23.4500
889  30.0000
890   7.7500

[891 rows x 1 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Standard Scaling for 'Fare'
scaler_standard = StandardScaler()
# print(data['Fare'].head())
data["Fare"] = scaler_standard.fit_transform(data[["Fare"]])
data.head()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_Q,Embarked_S,Pclass_2,Pclass_3
0,1,0,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,-0.502445,NaN,False,True,False,True
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,0.786845,C85,False,False,False,False
2,3,1,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,-0.488854,NaN,False,True,False,True
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,0.420730,C123,False,True,False,False
4,5,0,"Allen, Mr. William Henry",1,35.0,0,0,373450,-0.486337,NaN,False,True,False,True

In [ ]:
data[['Fare']]

         Fare
0   -0.502445
1    0.786845
2   -0.488854
3    0.420730
4   -0.486337
..        ...
886 -0.386671
887 -0.044381
888 -0.176263
889 -0.044381
890 -0.492378

[891 rows x 1 columns]

In [ ]:
# Min-Max Scaling for 'Age'
scaler_minmax = MinMaxScaler()
data["Age"] = scaler_minmax.fit_transform(data[["Age"]])
data.head()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_Q,Embarked_S,Pclass_2,Pclass_3
0,1,0,"Braund, Mr. Owen Harris",1,0.271174,1,0,A/5 21171,-0.502445,NaN,False,True,False,True
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,0.472229,1,0,PC 17599,0.786845,C85,False,False,False,False
2,3,1,"Heikkinen, Miss. Laina",0,0.321438,0,0,STON/O2. 3101282,-0.488854,NaN,False,True,False,True
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,0.434531,1,0,113803,0.420730,C123,False,True,False,False
4,5,0,"Allen, Mr. William Henry",1,0.434531,0,0,373450,-0.486337,NaN,False,True,False,True

In [ ]:
data[["Fare"]].max()

Fare    9.667167
dtype: float64

In [ ]:
scaler_minmax.inverse_transform([[0.5]])

array([[40.21]])

In [ ]:
scaler_standard.inverse_transform([[0.5]])

array([[57.03697519]])

## Step 5: Binarization

In [ ]:
from sklearn.preprocessing import Binarizer

binarizer = Binarizer(threshold=0.5)
data["Age_binarized"] = binarizer.fit_transform(data[["Age"]])
print("\nAfter binarizing 'Age':\n")
data[["Age", "Age_binarized"]].head()

After binarizing 'Age':

        Age  Age_binarized
0  0.271174            0.0
1  0.472229            0.0
2  0.321438            0.0
3  0.434531            0.0
4  0.434531            0.0

## Step 6: Discretization

In [ ]:
data["Fare"].min()

-0.6484216535389205

In [ ]:
data["Fare"].max()

9.667166525013505

In [ ]:
(9.667166525013505+0.6484216535389205)/3

3.4385293928508083

In [ ]:
(9.667166525013505+0.6484216535389205)/3
#1st bin -0.6484216535389205 t0 2.790107739311888
#2nd bin 2.790107739311888 to 6.228637132162696
#3rd bin 6.228637132162696 to 9.667166525013505

3.4385293928508083

In [ ]:
data[data["Fare"]>6.228637132162696]

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_Q,Embarked_S,Pclass_2,Pclass_3,Age_binarized,Fare_binned,Fare_binned1
258,259,1,"Ward, Miss. Anna",0,0.434531,0,0,PC 17755,9.667167,NaN,False,False,False,False,0.0,2.0,2.0
679,680,1,"Cardeza, Mr. Thomas Drake Martinez",1,0.447097,0,1,PC 17755,9.667167,B51 B53 B55,False,False,False,False,0.0,2.0,2.0
737,738,1,"Lesurer, Mr. Gustave J",1,0.434531,0,0,PC 17755,9.667167,B101,False,False,False,False,0.0,2.0,2.0

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer
[]
discretizer = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="uniform")
data["Fare_binned"] = discretizer.fit_transform(data[["Fare"]])
print("\nAfter discretizing 'Fare':\n")
data[["Fare", "Fare_binned"]].head(1)

After discretizing 'Fare':

       Fare  Fare_binned
0 -0.502445          0.0

In [ ]:
data.groupby("Fare_binned")["Fare"].min()

Fare_binned
0.0   -0.648422
1.0    3.606793
2.0    9.667167
Name: Fare, dtype: float64

In [ ]:
data.groupby("Fare_binned")["Fare"].sum()

Fare_binned
0.0   -99.507371
1.0    70.505871
2.0    29.001500
Name: Fare, dtype: float64

In [ ]:
data.groupby("Fare_binned")["Fare"].count()

Fare_binned
0.0    871
1.0     17
2.0      3
Name: Fare, dtype: int64

In [ ]:
data['Fare'].mean()

np.float64(3.987332972840069e-18)

In [ ]:
data['Fare'].median()

-0.3573908580066095

In [ ]:
# discretizer = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="quantile")
# data["Fare_binned1"] = discretizer.fit_transform(data[["Fare"]])
# data.groupby("Fare_binned1")["Fare"].count()

In [ ]:
# for a,b in data[["Fare", "Fare_binned"]].groupby("Fare_binned"):
#   print(a,b)

## Step 7: Polynomial Features

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=3, include_bias=True)
poly_features = poly.fit_transform(data[["Age", "Fare"]])
poly_feature_names = poly.get_feature_names_out(["Age", "Fare"])
data[poly_feature_names] = poly_features
data.head(2)

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,...,Pclass_3,Fare_binned,1,Age^2,Age Fare,Fare^2,Age^3,Age^2 Fare,Age Fare^2,Fare^3
0,1,0,"Braund, Mr. Owen Harris",1,0.271174,1,0,A/5 21171,-0.502445,NaN,...,True,0.0,1.0,0.073535,-0.136250,0.252451,0.019941,-0.036947,0.068458,-0.126843
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,0.472229,1,0,PC 17599,0.786845,C85,...,False,0.0,1.0,0.223000,0.371571,0.619126,0.105307,0.175467,0.292369,0.487156

## Step 8: Power Transformation

In [ ]:
from sklearn.preprocessing import PowerTransformer

power_transformer = PowerTransformer()
data["Fare_power"] = power_transformer.fit_transform(data[["Fare"]])
print("\nAfter power transforming 'Fare':\n", data[["Fare", "Fare_power"]].head())

After power transforming 'Fare':
        Fare  Fare_power
0 -0.502445   -0.991127
1  0.786845    1.541572
2 -0.488854   -0.919992
3  0.420730    1.305559
4 -0.486337   -0.906989

In [ ]:
print(data['Fare'].mean())
print(data['Fare'].median())

3.987332972840069e-18
-0.3573908580066095

In [ ]:
data['Fare_power'].mean()

np.float64(-4.386066270124075e-17)

In [ ]:
data['Fare_power'].median()

-0.30898326130304576

## Step 9: Feature Selection

In [ ]:
from sklearn.feature_selection import SelectKBest, f_classif

# Dropping non-numeric columns
data_numeric = data.drop(["Name", "Ticket", "Cabin"], axis=1)

# Define features and target
X = data_numeric.drop("Survived", axis=1)
y = data_numeric["Survived"]

# Apply SelectKBest
selector = SelectKBest(score_func=f_classif, k=10)
X_new = selector.fit_transform(X, y)
selected_features = X.columns[selector.get_support(indices=True)]
selected_features

/usr/local/lib/python3.12/dist-packages/sklearn/feature_selection/_univariate_selection.py:111: UserWarning: Features [11] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/feature_selection/_univariate_selection.py:112: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

Index(['Sex', 'Fare', 'Embarked_S', 'Pclass_3', 'Fare_binned', 'Age Fare',
       'Fare^2', 'Age^2 Fare', 'Age Fare^2', 'Fare_power'],
      dtype='object')

In [ ]:
selected_features

Index(['Sex', 'Fare', 'Embarked_S', 'Pclass_3', 'Fare_binned1', 'Age Fare',
       'Fare^2', 'Age^2 Fare', 'Age Fare^2', 'Fare_power'],
      dtype='object')

## Step 10: Splitting the Data

In [ ]:
from sklearn.model_selection import train_test_split

# Using the selected features
X = data[selected_features]  # Use only selected features for training
y = data["Survived"]

# Splitting into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("\nFirst 5 rows of training set:\n", X_train.head())

In [ ]:
# X_train, X_test, y_train, y_test = train_test_split(
#     X,
#     y,
#     test_size=0.2,
#     random_state=42,
#     stratify=y  # <--- This is the magic addition!
# )

1. Handling Missing Values

Purpose: Missing values can cause errors in machine learning algorithms or lead to biased models if not handled properly.

Effect: Imputing with the median for numeric columns ensures that extreme values don’t unduly influence the imputed value. For categorical columns, using the most frequent category helps avoid creating artificial patterns by filling missing entries with a reasonable, frequently occurring value.

Modeling Impact: Filling missing values prevents data loss and ensures that each feature can contribute effectively to the model without gaps.

2. Encoding Categorical Variables

Purpose: Machine learning models generally cannot handle categorical variables directly, as they require numerical inputs.

Effect: Label encoding binary categorical features, like Sex, converts them into numerical form, while one-hot encoding for multi-class features, like Embarked and Pclass, ensures that the model doesn’t assume any ordinal relationship between categories.

Modeling Impact: Encoding enables the model to learn from categorical features without assuming ordinal relationships, improving interpretability and performance for these variables.

3. Feature Scaling

Purpose: Different features in the dataset may have vastly different scales, which can lead to biased model behavior (favoring features with larger scales).

Effect: Standard scaling (Fare) and min-max scaling (Age) ensure that all features contribute equally to the model, especially in distance-based algorithms like KNN or SVM.

Modeling Impact: Scaling helps the model converge faster and provides a balanced treatment for all features, leading to more stable and reliable performance.

4. Binarization

Purpose: For some features, transforming continuous values into binary categories (e.g., Age) can be helpful for simplifying complex distributions or highlighting specific distinctions (e.g., minor vs. adult).

Effect: Binarizing Age at a threshold of 0.5 (in the scaled data) separates passengers into two groups (young vs. old), which might provide an alternate representation of age with specific modeling insights.

Modeling Impact: This approach can make certain features more interpretable and lead to better performance in cases where binary decisions or groups are more meaningful.

5. Discretization

Purpose: Discretizing continuous features into discrete bins can sometimes improve model performance by reducing noise and capturing distinct groups.

Effect: Dividing Fare into three bins (low, medium, high) allows the model to treat fare categories distinctly rather than trying to interpret a continuous scale, which may enhance its ability to make categorical distinctions.

Modeling Impact: Discretization can simplify complex distributions, making it easier for certain models (like tree-based models) to understand the feature’s impact.

6. Polynomial Features

Purpose: Polynomial features capture interactions between features and can reveal non-linear relationships.

Effect: Generating interaction terms and higher-degree features for Age and Fare introduces quadratic relationships, allowing the model to capture more complex dependencies between these features.

Modeling Impact: Polynomial features can improve the model’s ability to learn non-linear patterns, especially in cases where interactions between features are crucial to predictions.

7. Power Transformation

Purpose: Power transformations reduce skewness, normalize distributions, and stabilize variance, which can be beneficial for heavily skewed features.

Effect: Applying a power transformation to Fare can make the distribution more Gaussian, which often improves performance, particularly for algorithms sensitive to skewed data.

Modeling Impact: Normalizing distributions with power transformations can make learning more effective by reducing bias introduced by skewed data.

8. Feature Selection

Purpose: Feature selection helps identify the most relevant features, reducing dimensionality and minimizing noise.

Effect: Using SelectKBest to choose the top features based on the ANOVA F-value selects features most related to the target variable (Survived), which reduces the dataset size and potentially improves model efficiency.

Modeling Impact: Feature selection can lead to simpler, faster, and sometimes more accurate models by focusing on only the most predictive features, thereby improving model generalization and reducing overfitting.

## Summary

In this assignment, you preprocessed the Titanic dataset by handling missing values, encoding categorical variables, scaling features, creating interaction terms with polynomial features, binarizing, discretizing, power transforming, and finally selecting the top features for the model input.

This preparation is essential for ensuring that the data is well-suited for machine learning models.

### Please answer the questions below to complete the experiment:

In [ ]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Good and Challenging for me" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]

In [ ]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "t more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? [16] 0s Additional:ssddmoregfdg \"\"\"\"\"gfdgas very difficult, what w\"colsadn\"nfh" #@param {type:"string"}

In [ ]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "No" #@param ["","Yes", "No"]

In [ ]:
#@title  Experiment walkthrough video? { run: "auto", vertical-output: true, display-mode: "form" }
Walkthrough = "Somewhat Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]

In [ ]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]

In [ ]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]

In [ ]:
#@title Run this cell to submit your notebook for Ungrading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")

Your submission is successful.
Ref Id: 15388
Date of submission:  12 May 2026
Time of submission:  19:30:11
View your submissions: https://learn-iiith.talentsprint.com/notebook_submissions