In [ ]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import numpy as np
import pandas as pd

In [ ]:
documents =[
    "the boy and the dog",
    "the cat and the dog",
    "andrew is a tall boy",
    "ram is a good boy.ratna is also good."
]

In [ ]:
vectorizer_bow = CountVectorizer()
X_bow = vectorizer_bow.fit_transform(documents)
print(vectorizer_bow.get_feature_names_out())
print(X_bow.toarray())

['also' 'and' 'andrew' 'boy' 'cat' 'dog' 'good' 'is' 'ram' 'ratna' 'tall'
 'the']
[[0 1 0 1 0 1 0 0 0 0 0 2]
 [0 1 0 0 1 1 0 0 0 0 0 2]
 [0 0 1 1 0 0 0 1 0 0 1 0]
 [1 0 0 1 0 0 2 2 1 1 0 0]]

In [ ]:
words = np.array(['and','boy','cat','dog','is','the']).reshape(-1,1)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)
X_enc = encoder.fit_transform(words)
print(X_enc)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
a = stop_words

In [ ]:
'also' in a

False

In [ ]:
from math import log

In [ ]:
log(2.5)

0.9162907318741551

In [ ]:
vectorizer_tfidf = TfidfVectorizer(stop_words=stop_words)
X_tfidf = vectorizer_tfidf.fit_transform(documents)
print(vectorizer_tfidf.get_feature_names_out())
print(X_tfidf.toarray())

['also' 'andrew' 'boy' 'cat' 'dog' 'good' 'ram' 'ratna' 'tall']
[[0.         0.         0.62922751 0.         0.77722116 0.
  0.         0.         0.        ]
 [0.         0.         0.         0.78528828 0.6191303  0.
  0.         0.         0.        ]
 [0.         0.64450299 0.41137791 0.         0.         0.
  0.         0.         0.64450299]
 [0.36742339 0.         0.23452159 0.         0.         0.73484678
  0.36742339 0.36742339 0.        ]]

In [ ]:
vectorizer_ngram = CountVectorizer(ngram_range=(2,2))
X_bigram = vectorizer_ngram.fit_transform(documents)
print(vectorizer_ngram.get_feature_names_out())
print(X_bigram.toarray())

['also good' 'and the' 'andrew is' 'boy and' 'boy ratna' 'cat and'
 'good boy' 'is also' 'is good' 'is tall' 'ram is' 'ratna is' 'tall boy'
 'the boy' 'the cat' 'the dog']
[[0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1]
 [0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0]
 [1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0]]

In [ ]:
data = [
    {'message':'i like the movie','sentiment':'positve'},
    {'message':'movie is not good','sentiment':'negative'},
    {'message':'wasted my time','sentiment':'negative'},
    {'message':'liked the movie','sentiment':'positve'},
]

In [ ]:
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer
import string
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.DataFrame(data)
df.head()

             message sentiment
0   i like the movie   positve
1  movie is not good  negative
2     wasted my time  negative
3    liked the movie   positve

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [ ]:
def preprocess(text):
    text = text.lower()
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]

    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return ' '.join(tokens)

In [ ]:
preprocess("studying the movie	")

'studying movie'

In [ ]:
df['clean_message']=df['message'].apply(preprocess)

In [ ]:
df.head()

             message sentiment clean_message
0   i like the movie   positve    like movie
1  movie is not good  negative    movie good
2     wasted my time  negative   wasted time
3    liked the movie   positve   liked movie

In [ ]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['clean_message'])
print(vectorizer.get_feature_names_out())
print(X.toarray())

['good' 'like' 'liked' 'movie' 'time' 'wasted']
[[0 1 0 1 0 0]
 [1 0 0 1 0 0]
 [0 0 0 0 1 1]
 [0 0 1 1 0 0]]

In [ ]:
y = df['sentiment'].map({'positve':1,'negative':0})
y

0    1
1    0
2    0
3    1
Name: sentiment, dtype: int64

In [ ]:
model = LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [ ]:
test_message = 'movie is not good'
test_message = preprocess(test_message)
X_test = vectorizer.transform([test_message])
prediction = model.predict(X_test)
prediction

array([0])